default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_development

test:
  <<: *default
  database: rails_api_test

production:
  <<: *default
  database: rails_api_production
  username: rails_api
  password: <%= ENV["RAILS_API_DATABASE_PASSWORD"] %>
