version: "3.9"
services:
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./.docker/volumes/postgres:/var/lib/postgresql/data
  rails_api:
    build:
      context: .
      dockerfile: .docker/rails_api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./rails_api:/rails_api
    ports:
      - "${REACT_APP_RAILS_API_PORT}:${REACT_APP_RAILS_API_PORT}"
    depends_on:
      postgres:
        condition: service_started

  react_ui:
    build:
      context: .
      dockerfile: .docker/react_ui/Dockerfile
    env_file:
      - .env
    volumes:
      - ./react_ui:/react_ui
    ports:
      - "${REACT_APP_REACT_UI_PORT}:${REACT_APP_REACT_UI_PORT}"
    depends_on:
      rails_api:
        condition: service_started

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    depends_on:
      react_ui:
        condition: service_started
      rails_api:
        condition: service_started
    restart: always
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.docker/certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
      - 443:443

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./.docker/certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
