version: "3.9"
networks:
  caddy:
services:
  postgres:
    image: postgres:16.0-alpine
    env_file:
      - .env
    volumes:
      - $PWD/.ops/volumes/postgres:/var/lib/postgresql/data
    networks:
      - caddy

  rails_api:
    build:
      context: .
      dockerfile: .ops/rails_api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./rails_api:/rails_api
    ports:
      - "${REACT_APP_RAILS_API_PORT}:${REACT_APP_RAILS_API_PORT}"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - caddy

  react_ui:
    build:
      context: .
      dockerfile: .ops/react_ui/Dockerfile
      # args:
      #   CACHEBUST: 1
    env_file:
      - .env
    volumes:
      - ./react_ui:/react_ui
    ports:
      - "${REACT_APP_REACT_UI_PORT}:${REACT_APP_REACT_UI_PORT}"
    depends_on:
      rails_api:
        condition: service_started
    networks:
      - caddy

  caddy:
    image: caddy/caddy:2.7.5-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/.ops/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy

volumes:
  caddy_data:
  caddy_config:
