#!/usr/bin/env bash

git pull

# Remove postgres volume to eliminate permissions
# issue where docker will create a new volume upon
# building which the user will not have access to
sudo rm -rf .docker/volumes/postgres

docker-compose up -d --build
