#!/usr/bin/env bash

# Generate environment variables
cp .env.example .env

# Set up front end
cd react_ui
asdf install nodejs 18.15.0
asdf local nodejs 18.15.0
npm install --global yarn
yarn install

# Set up back end
cd ../rails_api
asdf install ruby 3.2.0
asdf local ruby 3.2.0
gem install bundler
bundle install

# Build docker containers/volumes
cd ..
./build
